server:
  port: 8080
  servlet:
    context-path: /api/spring-project-generator

logging:
  level:
    root: INFO

project:
  generator:
    available-packages: controllers,services,repositories,models,exceptions,config,common,constants,aspects,entities,utils
    available-apis: GET,POST,PUT,DELETE
    available-java-versions: 17,21

delete-files-after-seconds: 60